name: Deploy Website
on:
    push:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Cach dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies
              run: npm ci
            - name: Lint code
              run: npm run lint
            - name: Run test
              run: npm test
    build:
        needs: test
        runs-on: ubuntu-latest
        outputs: # Outputs defined in a build job
            script-file: ${{ steps.publish.outputs.script-file }} # Accessing the output of the 'publish' step
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Build website
              run: npm run build
            - name: Publish Js filename
              id: publish
              run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';' # Appending the output to the $GITHUB_OUTPUT environment variable, this allows us to access the output of this step in other steps
            - name: Upload artitacts
              uses: actions/upload-artifact@v4 # Uploading Build files as artifact
              with: # Configuration for uploading artifacts
                  name: dist-files # Name of the artifact
                  path:
                      | # Path to the files to be uploaded, dist folder and package.json
                      dist
                      package.json

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Get Build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: dist-files # Name of the artifact
            - name: Output contents
              run: ls # Listing contents of the artifact
            - name: Output script filename
              run: echo "${{ needs.build.outputs.script-file }}" # Accessing the output of the 'build' job
            - name: Deploy Website
              run: echo "Deploying..."
